# Generated by Django 5.0.3 on 2024-03-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=20),
            preserve_default=False,
        ),
    ]
