# Generated by Django 5.0.3 on 2024-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='size_of_engine',
            field=models.CharField(choices=[('1000cm dan kichik', 999), ('1001 - 3000cm gacha', 1000)], max_length=19),
        ),
    ]
