# Generated by Django 5.0.3 on 2024-03-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_car_result_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='size_of_engine',
            field=models.CharField(choices=[('999', '1000cm dan kichik'), ('1000', '1001 - 3000cm gacha')], max_length=19),
        ),
    ]
