# Generated by Django 5.0.3 on 2024-03-25 10:50

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_car_size_of_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=base.models.YearField(blank=True, null=True),
        ),
    ]
