# Generated by Django 5.0.3 on 2024-03-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type_of_car',
            field=models.CharField(choices=[(0, 'Benzin-Dizel'), (1, 'Elektr-Gibrid')], max_length=20),
        ),
    ]
