# Generated by Django 5.0.3 on 2024-03-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_car_type_of_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='country',
        ),
        migrations.AlterField(
            model_name='car',
            name='type_of_car',
            field=models.CharField(choices=[('Benzin-Dizel', 'Benzin-Dizel'), ('Elektr-Gibrid', 'Elektr-Gibrid')], max_length=20),
        ),
    ]
