# Generated by Django 5.0.3 on 2024-03-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_car_price_alter_car_size_of_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='size_of_engine',
            field=models.CharField(choices=[('1000cm dan kichik', '1000cm dan kichik'), ('1000cm dan - 2000cm gacha', '1000cm dan - 2000cm gacha'), ('2000cm dan - 3000cm gacha', '2000cm dan - 3000cm gacha'), ('3000cm dan - 3500cm gacha', '3000cm dan - 3500cm gacha'), ('3500cm dan katta', '3500cm dan katta')], max_length=50),
        ),
    ]
